// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/customerpb/customer.proto

package customerpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bill struct {
	Valor                int64    `protobuf:"varint,2,opt,name=valor,proto3" json:"valor,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bill) Reset()         { *m = Bill{} }
func (m *Bill) String() string { return proto.CompactTextString(m) }
func (*Bill) ProtoMessage()    {}
func (*Bill) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff5100f4a45e2470, []int{0}
}

func (m *Bill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bill.Unmarshal(m, b)
}
func (m *Bill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bill.Marshal(b, m, deterministic)
}
func (m *Bill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bill.Merge(m, src)
}
func (m *Bill) XXX_Size() int {
	return xxx_messageInfo_Bill.Size(m)
}
func (m *Bill) XXX_DiscardUnknown() {
	xxx_messageInfo_Bill.DiscardUnknown(m)
}

var xxx_messageInfo_Bill proto.InternalMessageInfo

func (m *Bill) GetValor() int64 {
	if m != nil {
		return m.Valor
	}
	return 0
}

func (m *Bill) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Customer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cpf                  string   `protobuf:"bytes,2,opt,name=cpf,proto3" json:"cpf,omitempty"`
	Nome                 string   `protobuf:"bytes,3,opt,name=nome,proto3" json:"nome,omitempty"`
	Endereco             string   `protobuf:"bytes,4,opt,name=endereco,proto3" json:"endereco,omitempty"`
	Dividas              []*Bill  `protobuf:"bytes,5,rep,name=dividas,proto3" json:"dividas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff5100f4a45e2470, []int{1}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Customer) GetCpf() string {
	if m != nil {
		return m.Cpf
	}
	return ""
}

func (m *Customer) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

func (m *Customer) GetEndereco() string {
	if m != nil {
		return m.Endereco
	}
	return ""
}

func (m *Customer) GetDividas() []*Bill {
	if m != nil {
		return m.Dividas
	}
	return nil
}

// message CreateCustomerRequest {
// 	Customer customer = 1;
// }
// message CreateCustomerResponse {
// 	string message = 1;
// }
type FindByDocumentRequest struct {
	Document             string   `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByDocumentRequest) Reset()         { *m = FindByDocumentRequest{} }
func (m *FindByDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*FindByDocumentRequest) ProtoMessage()    {}
func (*FindByDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff5100f4a45e2470, []int{2}
}

func (m *FindByDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByDocumentRequest.Unmarshal(m, b)
}
func (m *FindByDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByDocumentRequest.Marshal(b, m, deterministic)
}
func (m *FindByDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByDocumentRequest.Merge(m, src)
}
func (m *FindByDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_FindByDocumentRequest.Size(m)
}
func (m *FindByDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByDocumentRequest proto.InternalMessageInfo

func (m *FindByDocumentRequest) GetDocument() string {
	if m != nil {
		return m.Document
	}
	return ""
}

type FindByDocumentResponse struct {
	Customer             *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FindByDocumentResponse) Reset()         { *m = FindByDocumentResponse{} }
func (m *FindByDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*FindByDocumentResponse) ProtoMessage()    {}
func (*FindByDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff5100f4a45e2470, []int{3}
}

func (m *FindByDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByDocumentResponse.Unmarshal(m, b)
}
func (m *FindByDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByDocumentResponse.Marshal(b, m, deterministic)
}
func (m *FindByDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByDocumentResponse.Merge(m, src)
}
func (m *FindByDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_FindByDocumentResponse.Size(m)
}
func (m *FindByDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindByDocumentResponse proto.InternalMessageInfo

func (m *FindByDocumentResponse) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func init() {
	proto.RegisterType((*Bill)(nil), "api.Bill")
	proto.RegisterType((*Customer)(nil), "api.Customer")
	proto.RegisterType((*FindByDocumentRequest)(nil), "api.FindByDocumentRequest")
	proto.RegisterType((*FindByDocumentResponse)(nil), "api.FindByDocumentResponse")
}

func init() { proto.RegisterFile("api/customerpb/customer.proto", fileDescriptor_ff5100f4a45e2470) }

var fileDescriptor_ff5100f4a45e2470 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4d, 0x4b, 0xf4, 0x40,
	0x10, 0x84, 0xc9, 0xc7, 0xbe, 0x6f, 0xd2, 0xab, 0xab, 0x34, 0x2a, 0x21, 0x22, 0x84, 0x78, 0x89,
	0x97, 0x28, 0xd9, 0x7f, 0x90, 0x15, 0xc1, 0xeb, 0x78, 0x13, 0x2f, 0xb3, 0x99, 0x16, 0x06, 0x92,
	0xcc, 0x98, 0x2f, 0xf0, 0xe8, 0x3f, 0x97, 0xcc, 0x26, 0x11, 0x65, 0x6f, 0xd5, 0x5d, 0xd4, 0x93,
	0xca, 0x34, 0xdc, 0x70, 0x2d, 0xef, 0x8b, 0xbe, 0xed, 0x54, 0x45, 0x8d, 0xde, 0x2f, 0x32, 0xd5,
	0x8d, 0xea, 0x14, 0x3a, 0x5c, 0xcb, 0xf8, 0x01, 0xdc, 0x5c, 0x96, 0x25, 0x5e, 0xc0, 0x6a, 0xe0,
	0xa5, 0x6a, 0x02, 0x3b, 0xb2, 0x12, 0x87, 0x1d, 0x06, 0x44, 0x70, 0x05, 0xef, 0x78, 0xe0, 0x44,
	0x56, 0xe2, 0x33, 0xa3, 0xe3, 0x2f, 0x0b, 0xbc, 0xdd, 0x44, 0xc2, 0x0d, 0xd8, 0x52, 0x04, 0x96,
	0xb1, 0x6d, 0x29, 0xf0, 0x1c, 0x9c, 0x42, 0xbf, 0x1b, 0x88, 0xcf, 0x46, 0x39, 0x22, 0x6a, 0x55,
	0xd1, 0x8c, 0x18, 0x35, 0x86, 0xe0, 0x51, 0x2d, 0xa8, 0xa1, 0x42, 0x05, 0xae, 0xd9, 0x2f, 0x33,
	0xde, 0xc2, 0x7f, 0x21, 0x07, 0x29, 0x78, 0x1b, 0xac, 0x22, 0x27, 0x59, 0x67, 0x7e, 0xca, 0xb5,
	0x4c, 0xc7, 0x92, 0x6c, 0x76, 0xe2, 0x2d, 0x5c, 0x3e, 0xc9, 0x5a, 0xe4, 0x9f, 0x8f, 0xaa, 0xe8,
	0x2b, 0xaa, 0x3b, 0x46, 0x1f, 0x3d, 0xb5, 0xdd, 0x48, 0x16, 0xd3, 0x6a, 0x6a, 0xb5, 0xcc, 0xf1,
	0x0e, 0xae, 0xfe, 0x86, 0x5a, 0xad, 0xea, 0x96, 0xf0, 0x0e, 0xbc, 0xf9, 0x6d, 0x4c, 0x6a, 0x9d,
	0x9d, 0x9a, 0x8f, 0xce, 0xbf, 0xc9, 0x16, 0x3b, 0x7b, 0x83, 0xb3, 0x79, 0xfb, 0x42, 0xcd, 0x20,
	0x0b, 0xc2, 0x67, 0xd8, 0xfc, 0xe6, 0x62, 0x68, 0xd2, 0x47, 0x1b, 0x86, 0xd7, 0x47, 0xbd, 0x43,
	0x91, 0xfc, 0xe4, 0x15, 0x7e, 0xee, 0xb5, 0xff, 0x67, 0xee, 0xb4, 0xfd, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0x71, 0x21, 0x82, 0x6e, 0xc8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerServiceClient interface {
	// rpc CreateCustomer (CreateCustomerRequest) returns (CreateCustomerResponse);
	FindByDocument(ctx context.Context, in *FindByDocumentRequest, opts ...grpc.CallOption) (*FindByDocumentResponse, error)
}

type customerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomerServiceClient(cc *grpc.ClientConn) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) FindByDocument(ctx context.Context, in *FindByDocumentRequest, opts ...grpc.CallOption) (*FindByDocumentResponse, error) {
	out := new(FindByDocumentResponse)
	err := c.cc.Invoke(ctx, "/api.CustomerService/FindByDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
type CustomerServiceServer interface {
	// rpc CreateCustomer (CreateCustomerRequest) returns (CreateCustomerResponse);
	FindByDocument(context.Context, *FindByDocumentRequest) (*FindByDocumentResponse, error)
}

// UnimplementedCustomerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServiceServer struct {
}

func (*UnimplementedCustomerServiceServer) FindByDocument(ctx context.Context, req *FindByDocumentRequest) (*FindByDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByDocument not implemented")
}

func RegisterCustomerServiceServer(s *grpc.Server, srv CustomerServiceServer) {
	s.RegisterService(&_CustomerService_serviceDesc, srv)
}

func _CustomerService_FindByDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).FindByDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CustomerService/FindByDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).FindByDocument(ctx, req.(*FindByDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindByDocument",
			Handler:    _CustomerService_FindByDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/customerpb/customer.proto",
}
