// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/customerpb/customer.proto

package customerpb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Customer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cpf                  string   `protobuf:"bytes,2,opt,name=cpf,proto3" json:"cpf,omitempty"`
	Nome                 string   `protobuf:"bytes,3,opt,name=nome,proto3" json:"nome,omitempty"`
	Endereco             string   `protobuf:"bytes,4,opt,name=endereco,proto3" json:"endereco,omitempty"`
	Dividas              string   `protobuf:"bytes,5,opt,name=dividas,proto3" json:"dividas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff5100f4a45e2470, []int{0}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Customer) GetCpf() string {
	if m != nil {
		return m.Cpf
	}
	return ""
}

func (m *Customer) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

func (m *Customer) GetEndereco() string {
	if m != nil {
		return m.Endereco
	}
	return ""
}

func (m *Customer) GetDividas() string {
	if m != nil {
		return m.Dividas
	}
	return ""
}

type CreateCustomerRequest struct {
	Customer             *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateCustomerRequest) Reset()         { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()    {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff5100f4a45e2470, []int{1}
}

func (m *CreateCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerRequest.Unmarshal(m, b)
}
func (m *CreateCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerRequest.Marshal(b, m, deterministic)
}
func (m *CreateCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerRequest.Merge(m, src)
}
func (m *CreateCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerRequest.Size(m)
}
func (m *CreateCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerRequest proto.InternalMessageInfo

func (m *CreateCustomerRequest) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type CreateCustomerResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCustomerResponse) Reset()         { *m = CreateCustomerResponse{} }
func (m *CreateCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerResponse) ProtoMessage()    {}
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff5100f4a45e2470, []int{2}
}

func (m *CreateCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerResponse.Unmarshal(m, b)
}
func (m *CreateCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerResponse.Marshal(b, m, deterministic)
}
func (m *CreateCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerResponse.Merge(m, src)
}
func (m *CreateCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerResponse.Size(m)
}
func (m *CreateCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerResponse proto.InternalMessageInfo

func (m *CreateCustomerResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FindByDocumentRequest struct {
	Document             string   `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByDocumentRequest) Reset()         { *m = FindByDocumentRequest{} }
func (m *FindByDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*FindByDocumentRequest) ProtoMessage()    {}
func (*FindByDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff5100f4a45e2470, []int{3}
}

func (m *FindByDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByDocumentRequest.Unmarshal(m, b)
}
func (m *FindByDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByDocumentRequest.Marshal(b, m, deterministic)
}
func (m *FindByDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByDocumentRequest.Merge(m, src)
}
func (m *FindByDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_FindByDocumentRequest.Size(m)
}
func (m *FindByDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByDocumentRequest proto.InternalMessageInfo

func (m *FindByDocumentRequest) GetDocument() string {
	if m != nil {
		return m.Document
	}
	return ""
}

type FindByDocumentResponse struct {
	Customer             *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FindByDocumentResponse) Reset()         { *m = FindByDocumentResponse{} }
func (m *FindByDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*FindByDocumentResponse) ProtoMessage()    {}
func (*FindByDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff5100f4a45e2470, []int{4}
}

func (m *FindByDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByDocumentResponse.Unmarshal(m, b)
}
func (m *FindByDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByDocumentResponse.Marshal(b, m, deterministic)
}
func (m *FindByDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByDocumentResponse.Merge(m, src)
}
func (m *FindByDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_FindByDocumentResponse.Size(m)
}
func (m *FindByDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindByDocumentResponse proto.InternalMessageInfo

func (m *FindByDocumentResponse) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func init() {
	proto.RegisterType((*Customer)(nil), "api.Customer")
	proto.RegisterType((*CreateCustomerRequest)(nil), "api.CreateCustomerRequest")
	proto.RegisterType((*CreateCustomerResponse)(nil), "api.CreateCustomerResponse")
	proto.RegisterType((*FindByDocumentRequest)(nil), "api.FindByDocumentRequest")
	proto.RegisterType((*FindByDocumentResponse)(nil), "api.FindByDocumentResponse")
}

func init() { proto.RegisterFile("api/customerpb/customer.proto", fileDescriptor_ff5100f4a45e2470) }

var fileDescriptor_ff5100f4a45e2470 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0xa5, 0xed, 0xaa, 0x75, 0xd4, 0x2a, 0x03, 0xbb, 0x84, 0x8a, 0x20, 0x3d, 0xe9, 0xa5, 0x42,
	0xf7, 0x0f, 0x5a, 0x11, 0xf6, 0xba, 0xde, 0xbc, 0x65, 0x9b, 0x51, 0x72, 0x68, 0x13, 0x9b, 0xb6,
	0xe0, 0x17, 0xf9, 0x9b, 0xb2, 0x31, 0xa9, 0xec, 0xd2, 0x83, 0xb7, 0x79, 0x6f, 0x32, 0xf3, 0xde,
	0x0b, 0x03, 0x77, 0x5c, 0xcb, 0xa7, 0x7a, 0x30, 0xbd, 0x6a, 0xa8, 0xd3, 0xbb, 0xa9, 0xcc, 0x75,
	0xa7, 0x7a, 0x85, 0x11, 0xd7, 0x32, 0x1b, 0x21, 0xae, 0x1c, 0x8d, 0x09, 0x84, 0x52, 0xb0, 0xe0,
	0x3e, 0x78, 0x38, 0xdf, 0x86, 0x52, 0xe0, 0x0d, 0x44, 0xb5, 0x7e, 0x67, 0xa1, 0x25, 0xf6, 0x25,
	0x22, 0x2c, 0x5a, 0xd5, 0x10, 0x8b, 0x2c, 0x65, 0x6b, 0x4c, 0x21, 0xa6, 0x56, 0x50, 0x47, 0xb5,
	0x62, 0x0b, 0xcb, 0x4f, 0x18, 0x19, 0x9c, 0x09, 0x39, 0x4a, 0xc1, 0x0d, 0x3b, 0xb1, 0x2d, 0x0f,
	0xb3, 0x12, 0x96, 0x55, 0x47, 0xbc, 0x27, 0xaf, 0xbe, 0xa5, 0xcf, 0x81, 0x4c, 0x8f, 0x8f, 0x10,
	0x7b, 0x9f, 0xd6, 0xca, 0x45, 0x71, 0x95, 0x73, 0x2d, 0xf3, 0xe9, 0xdd, 0xd4, 0xce, 0x0a, 0x58,
	0x1d, 0xef, 0x30, 0x5a, 0xb5, 0x86, 0xf6, 0xba, 0x0d, 0x19, 0xc3, 0x3f, 0xc8, 0xc5, 0xf1, 0x30,
	0x5b, 0xc3, 0xf2, 0x45, 0xb6, 0xa2, 0xfc, 0x7a, 0x56, 0xf5, 0xd0, 0x50, 0xdb, 0x7b, 0xdd, 0x14,
	0x62, 0xe1, 0x28, 0x37, 0x33, 0xe1, 0xac, 0x82, 0xd5, 0xf1, 0x90, 0x13, 0xfa, 0xbf, 0xdb, 0xe2,
	0x3b, 0x80, 0x6b, 0x4f, 0xbf, 0x52, 0x37, 0xca, 0x9a, 0x70, 0x03, 0xc9, 0x61, 0x02, 0x4c, 0x7f,
	0xc7, 0xe7, 0xbe, 0x26, 0xbd, 0x9d, 0xed, 0x39, 0x27, 0x1b, 0x48, 0x0e, 0x3d, 0xba, 0x55, 0xb3,
	0x69, 0xdd, 0xaa, 0xf9, 0x50, 0xe5, 0xe5, 0x1b, 0xfc, 0x5d, 0xcd, 0xee, 0xd4, 0x5e, 0xcb, 0xfa,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xfd, 0x9f, 0x02, 0x4e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerServiceClient interface {
	CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerResponse, error)
	FindByDocument(ctx context.Context, in *FindByDocumentRequest, opts ...grpc.CallOption) (*FindByDocumentResponse, error)
}

type customerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomerServiceClient(cc *grpc.ClientConn) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerResponse, error) {
	out := new(CreateCustomerResponse)
	err := c.cc.Invoke(ctx, "/api.CustomerService/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) FindByDocument(ctx context.Context, in *FindByDocumentRequest, opts ...grpc.CallOption) (*FindByDocumentResponse, error) {
	out := new(FindByDocumentResponse)
	err := c.cc.Invoke(ctx, "/api.CustomerService/FindByDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
type CustomerServiceServer interface {
	CreateCustomer(context.Context, *CreateCustomerRequest) (*CreateCustomerResponse, error)
	FindByDocument(context.Context, *FindByDocumentRequest) (*FindByDocumentResponse, error)
}

// UnimplementedCustomerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServiceServer struct {
}

func (*UnimplementedCustomerServiceServer) CreateCustomer(ctx context.Context, req *CreateCustomerRequest) (*CreateCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (*UnimplementedCustomerServiceServer) FindByDocument(ctx context.Context, req *FindByDocumentRequest) (*FindByDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByDocument not implemented")
}

func RegisterCustomerServiceServer(s *grpc.Server, srv CustomerServiceServer) {
	s.RegisterService(&_CustomerService_serviceDesc, srv)
}

func _CustomerService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CustomerService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).CreateCustomer(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_FindByDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).FindByDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CustomerService/FindByDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).FindByDocument(ctx, req.(*FindByDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _CustomerService_CreateCustomer_Handler,
		},
		{
			MethodName: "FindByDocument",
			Handler:    _CustomerService_FindByDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/customerpb/customer.proto",
}
